PROJ=soc
SYSTEM_FREQUENCY ?= 55000000

RM             = rm -rf
VERILOG_FILES := pll.v \
								 bram.v \
								 tx_uart.v \
								 rx_uart.v \
								 fifo.v \
								 qqspi.v \
								 clint.v \
								 spi_nor_flash.v \
								 spi.v \
								 gpio.v \
								 pwm.v \
								 cache.v \
								 icache.v \
								 sdram/mt48lc16m16a2_ctrl.v \
								 kianv_harris_edition/kianv_harris_mc_edition.v \
								 kianv_harris_edition/control_unit.v  \
								 kianv_harris_edition/datapath_unit.v \
								 kianv_harris_edition/register_file.v \
								 kianv_harris_edition/design_elements.v \
								 kianv_harris_edition/design_elements_fpgacpu_ca.v \
								 kianv_harris_edition/alu.v \
								 kianv_harris_edition/main_fsm.v \
								 kianv_harris_edition/extend.v \
								 kianv_harris_edition/alu_decoder.v \
								 kianv_harris_edition/store_alignment.v \
								 kianv_harris_edition/store_decoder.v \
								 kianv_harris_edition/load_decoder.v \
								 kianv_harris_edition/load_alignment.v \
								 kianv_harris_edition/multiplier_extension_decoder.v \
								 kianv_harris_edition/divider.v \
								 kianv_harris_edition/multiplier.v \
								 kianv_harris_edition/divider_decoder.v \
								 kianv_harris_edition/multiplier_decoder.v \
								 kianv_harris_edition/csr_exception_handler.v \
								 kianv_harris_edition/csr_decoder.v \
								 kianv_harris_edition/sv32.v \
								 kianv_harris_edition/sv32_table_walk.v \
								 kianv_harris_edition/sv32_translate_instruction_to_physical.v \
								 kianv_harris_edition/sv32_translate_data_to_physical.v \
								 kianv_harris_edition/tag_ram.v

all: ${PROJ}.bit
%.json: %.v
	yosys -DSYSTEM_CLK=${SYSTEM_FREQUENCY} -p "synth_ecp5  -abc9 -json $@ -top ${PROJ}" ${VERILOG_FILES} $<

%_out.config: %.json
	nextpnr-ecp5  --freq 350 --timing-allow-fail --router router1 --json $< --textcfg $@ --25k --speed 6 --package CABGA256 --lpf icesugar-pro.lpf

%.bit: %_out.config
	ecppack --compress --input $< --bit $@

clean:
	$(RM) -f ${PROJ}.bit ${PROJ}_out.config ${PROJ}.json

.PHONY: clean
