name: Build OS KianV RV32IMA SV32 Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential device-tree-compiler cpio rsync file wget unzip bc

    - name: Build OS
      working-directory: linux_socs/LinuxSoC/os/linux/buildroot-kianv-soc
      run: |
        make
        make fw_payload.rle

    - name: Prepare artifact
      working-directory: linux_socs/LinuxSoC/os/linux/buildroot-kianv-soc
      run: |
        mkdir -p artifact_files
        cp buildroot/output/images/rootfs.ext2 fw_payload.rle artifact_files

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux_kianv_riscv_soc_rv32ima_sv32
        path: linux_socs/LinuxSoC/os/linux/buildroot-kianv-soc/artifact_files
